/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionpersonnel;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cedric Greufeille
 */
public class Detail_Mission extends javax.swing.JDialog {

    private Integer i;
    private int nbComp;
    private int nbPers;
    
    /**
     * Creates new form Detail_Mission
     */
    public Detail_Mission(Integer i) {
        initComponents();
        this.setSize(getWidth() + 16, getHeight() + 39);
        this.setResizable(false);
        this.setLocationRelativeTo(null);  
        this.i = i;
        recupererDonnees();
    }

    /**
     * Creates new form Detail_Mission
     */
    public Detail_Mission() {
        initComponents();
        this.setSize(getWidth() + 16, getHeight() + 39);
        this.setResizable(false);
        this.setLocationRelativeTo(null);   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tTitre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPers = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabComp = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NB1 = new javax.swing.JLabel();
        NB2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(248, 249, 250));

        tTitre.setFont(new java.awt.Font("Nunito Sans", 0, 30)); // NOI18N
        tTitre.setForeground(new java.awt.Color(74, 74, 74));
        tTitre.setText("Details de la Mission");

        jScrollPane1.setForeground(new java.awt.Color(74, 74, 74));
        jScrollPane1.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        tabPers.setAutoCreateRowSorter(true);
        tabPers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Compétence", "Id", "Nom", "Prénom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabPers);

        jScrollPane2.setForeground(new java.awt.Color(74, 74, 74));
        jScrollPane2.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N

        tabComp.setAutoCreateRowSorter(true);
        tabComp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nb necessaire", "Code", "Nom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabComp);

        jLabel1.setFont(new java.awt.Font("Nunito Sans", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(74, 74, 74));
        jLabel1.setText("Compétences :");

        jLabel2.setFont(new java.awt.Font("Nunito Sans", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(74, 74, 74));
        jLabel2.setText("Personnel :");

        jLabel3.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(74, 74, 74));
        jLabel3.setText("Cette mission nécéssite ");

        jLabel4.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(74, 74, 74));
        jLabel4.setText("compétences.");

        jLabel5.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(74, 74, 74));
        jLabel5.setText("personnes.");

        jLabel6.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(74, 74, 74));
        jLabel6.setText("Cette mission nécéssite ");

        jButton1.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(74, 74, 74));
        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NB1.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N
        NB1.setForeground(new java.awt.Color(74, 74, 74));
        NB1.setText("NB");

        NB2.setFont(new java.awt.Font("Nunito Sans", 0, 14)); // NOI18N
        NB2.setForeground(new java.awt.Color(74, 74, 74));
        NB2.setText("NB");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tTitre)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel3))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NB1)
                                    .addComponent(NB2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(NB1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(NB2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void recupererDonnees() { 
        Mission mi = null;
        for (Mission m : MissionDAO.missions) {
            if (m.getId() == i) {
                mi = m;
            }
        }
        Object[][] data = new Object[mi.getCompetences().keySet().size()][3];
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        int in = 0;
        for (String s : mi.getCompetences().keySet()) {
            data[in][0] = mi.getCompetences().get(s);
            data[in][1] = s;
            String nom = null;
            for (Competence c : CompetenceDAO.competences) {
                if (c.getId().equals(s)) {
                    nom = c.getName();
                }
            }
            data[in][2] = nom;
            this.nbComp += mi.getCompetences().get(s);
            in++;
        }
        String[] header = new String[] {"NB Nécessaire", "Code", "Nom"};
        DefaultTableModel tbm = new DefaultTableModel(data, header);
        tabComp.setModel(tbm);
        in = 0;
        Object[][] donnees = new Object[mi.getParticipants().size()][4];
        for (Integer inte : mi.getParticipants().keySet()) {
            String toString = "";
            Personnel per = null;
            for (Personnel p : mi.getParticipants().values()) {
                if (p.getId() == inte) {
                    per = p;
                    for (Competence c : p.competences) {
                        toString = toString + " " + c.getId();
                    }
                }
            }
            donnees[in][0] = toString;
            donnees[in][1] = inte;
            donnees[in][2] = per.getName();
            donnees[in][3] = per.getPrenom();
            in++;
            this.nbPers++;
        }
        String[] entete = new String[] {"Compétences", "Code", "Nom", "Prenom"};
        DefaultTableModel tb = new DefaultTableModel(donnees, entete);
        tabPers.setModel(tb);
        NB1.setText(String.valueOf(nbComp));
        NB2.setText(String.valueOf(nbPers));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail_Mission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail_Mission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail_Mission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail_Mission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Detail_Mission dialog = new Detail_Mission();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NB1;
    private javax.swing.JLabel NB2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel tTitre;
    private javax.swing.JTable tabComp;
    private javax.swing.JTable tabPers;
    // End of variables declaration//GEN-END:variables
}
