

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionpersonnel;

import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * <b> Cette interface permet la modification d'un employé</b>
 * 
 * @author jonathan detrier
 */

public class Modify_Employe extends javax.swing.JDialog {

    private JFrame parent;
    private String id;
    private String name;
    private String prenom;
    private String dateE;
    private DefaultListModel modele;
    
     /**
     * Creates new form Modify_Employe
     * @param parent
     *  Frame parent Menu_Personnel
     * @param modal
     *      boolean modal
     * @param id
     *      String id
     * @throws java.io.IOException
     *      Exception
     * @throws java.text.ParseException
     *      ParseException
     */
    public Modify_Employe(JFrame parent, boolean modal, String id) throws IOException, ParseException {
        super(parent, modal);
        try{
            this.parent = parent;
            this.id = id;
            this.modele = new DefaultListModel();
            initComponents();
            recupererCompetencesPersonnelParent();
            this.setResizable(false);
            this.setLocationRelativeTo(null);
            recupererCompetences();
        }catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Le format de la date n'est pas bon. Veuillez entrer une date au format : jj/mm/aaaa", "Erreur :" + ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        identite = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        nomTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        prenomTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        ligne = new javax.swing.JSeparator();
        competences = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        competencesEmployer = new javax.swing.JScrollPane();
        competencesEmployerListe = new JList(modele);
        quit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        competencesDispo = new javax.swing.JScrollPane();
        competencesDisponiblesListe = new JList(modele);

        setTitle("Ajouter un employé");

        bg.setBackground(new java.awt.Color(248, 249, 250));

        title.setFont(new java.awt.Font("Nunito Sans Light", 0, 30)); // NOI18N
        title.setForeground(new java.awt.Color(74, 74, 74));
        title.setText("Modifier un employé");

        identite.setFont(new java.awt.Font("Nunito Sans Light", 0, 26)); // NOI18N
        identite.setForeground(new java.awt.Color(74, 74, 74));
        identite.setText("Identité");

        nom.setFont(new java.awt.Font("Nunito Sans", 0, 16)); // NOI18N
        nom.setText("Nom");

        nomTextField.setFont(new java.awt.Font("Nunito Sans", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Nunito Sans", 0, 16)); // NOI18N
        jLabel5.setText("Prénom");

        prenomTextField.setFont(new java.awt.Font("Nunito Sans", 0, 16)); // NOI18N

        dateTextField.setFont(new java.awt.Font("Nunito Sans", 0, 16)); // NOI18N

        date.setFont(new java.awt.Font("Nunito Sans", 0, 16)); // NOI18N
        date.setText("Date d'entrée");

        competences.setFont(new java.awt.Font("Nunito Sans Light", 0, 26)); // NOI18N
        competences.setForeground(new java.awt.Color(74, 74, 74));
        competences.setText("Compétences");

        add.setText(">");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        remove.setText("<");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        competencesEmployerListe.setFont(new java.awt.Font("Nunito Sans", 0, 16)); // NOI18N
        competencesEmployerListe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        competencesEmployerListe.setSelectionBackground(new java.awt.Color(229, 101, 144));
        competencesEmployer.setViewportView(competencesEmployerListe);

        quit.setFont(new java.awt.Font("Nunito Sans", 0, 16)); // NOI18N
        quit.setForeground(new java.awt.Color(74, 74, 74));
        quit.setText("Quitter");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Nunito Sans", 0, 16)); // NOI18N
        save.setForeground(new java.awt.Color(74, 74, 74));
        save.setText("Enregistrer");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        competencesDisponiblesListe.setFont(new java.awt.Font("Nunito Sans", 0, 16)); // NOI18N
        competencesDisponiblesListe.setSelectionBackground(new java.awt.Color(229, 101, 144));
        competencesDispo.setViewportView(competencesDisponiblesListe);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(competences)
                        .addGap(375, 375, 375))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(nom)
                        .addGap(18, 18, 18)
                        .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(identite)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(prenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(date)
                                .addGap(18, 18, 18)
                                .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64))))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ligne)
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(competencesDispo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(add)
                                .addComponent(remove))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                            .addComponent(competencesEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bgLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(quit)
                            .addGap(45, 45, 45)
                            .addComponent(save)
                            .addGap(266, 266, 266))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(identite, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom)
                    .addComponent(jLabel5)
                    .addComponent(prenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(ligne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(competences)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(competencesEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(competencesDispo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(add)
                        .addGap(29, 29, 29)
                        .addComponent(remove)))
                .addGap(33, 33, 33)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(quit))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        saveChanges();
        this.dispose();
    }//GEN-LAST:event_saveActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        Verification_Add_Employe vae = new Verification_Add_Employe(parent, true, this);
        vae.setAlwaysOnTop(true);
        vae.setVisible(true);
    }//GEN-LAST:event_quitActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        supprimerCompetence();
    }//GEN-LAST:event_removeActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        addCompetenceToPersonnel();
    }//GEN-LAST:event_addActionPerformed

    public void saveChanges() {
        PersonnelDAO p = new PersonnelDAO();
        for (Personnel pe : PersonnelDAO.personnels) {
            if (pe.getId() == Integer.parseInt(id)) {
                try {
                    if (nomTextField.getText().isEmpty() || prenomTextField.getText().isEmpty() || dateTextField.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Veuillez entrer l'ensemble des données demandées (Nom, prénom et Date d'entrée)", "Erreur : Champs requis", JOptionPane.ERROR_MESSAGE);
                    }
                    else {
			pe.setNom(nomTextField.getText());
			pe.setPrenom(prenomTextField.getText());
			DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
			pe.setDateE(df.parse(dateTextField.getText()));
                    }
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(this, "Le format de la date n'est pas bon. Veuillez entrer une date au format : jj/mm/aaaa", "Erreur :" + ex.getMessage(), JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }
    
    public void recupererCompetences() throws IOException {
        CompetenceDAO c = new CompetenceDAO();
        c.recupererCompetences();
	Vector<String> model = new Vector<>();
        for (Competence co : CompetenceDAO.competences) {
            model.add(co.getName());
            //choisirComboBox1.addItem(s);
        }
	competencesDisponiblesListe.setListData(model);
    }
    
    public void addCompetenceToPersonnel() {
        //String text = choisirComboBox1.getSelectedItem().toString();
        String text = competencesDisponiblesListe.getSelectedValue();
        if (!modele.contains(text)) {
            modele.addElement(text);
            competencesEmployerListe.setModel(modele);
            Competence temp = null;
            for (Competence co : CompetenceDAO.competences) {
                if (text.equals(co.getName())) {
                    temp = co;
                }
            }
            for (Personnel pe : PersonnelDAO.personnels) {
                if (pe.getId() == Integer.parseInt(id)) {
                    
                    pe.competences.add(temp);
                }
            }
        }  
    }
    
    public void recupererCompetencesPersonnelParent() throws IOException, ParseException {
        Vector<String> model = new Vector<>();
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        for (Personnel pe : PersonnelDAO.personnels) {
            if (pe.getId() == Integer.parseInt(this.id)) {
                this.name = pe.getName();
                this.prenom = pe.getPrenom();
                this.dateE = df.format(pe.getDateE());
                nomTextField.setText(this.name);
                prenomTextField.setText(this.prenom);
                dateTextField.setText(this.dateE);
                for (Competence c : pe.competences) {
                    modele.addElement(c.getName());
                }
            }
        }
        competencesEmployerListe.setModel(modele);
    }
    
    public void supprimerCompetence() {
        String text = competencesEmployerListe.getSelectedValue();
        int del = -20;
        modele.remove(modele.indexOf(text));
        competencesEmployerListe.setModel(modele);
        for (Personnel p : PersonnelDAO.personnels) {
            if (id.equals(String.valueOf(p.getId()))) {
                for (Competence co : p.competences) {
                    if (co.getName().equals(text)) {
                        del = p.competences.indexOf(co);
                    }
                }
                p.competences.remove(del);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    Modify_Employe dialog = new Modify_Employe(new javax.swing.JFrame(), true, new String());
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Add_Employe.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(Add_Employe.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel competences;
    private javax.swing.JScrollPane competencesDispo;
    private javax.swing.JList<String> competencesDisponiblesListe;
    private javax.swing.JScrollPane competencesEmployer;
    private javax.swing.JList<String> competencesEmployerListe;
    private javax.swing.JLabel date;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel identite;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator ligne;
    private javax.swing.JLabel nom;
    private javax.swing.JTextField nomTextField;
    private javax.swing.JTextField prenomTextField;
    private javax.swing.JButton quit;
    private javax.swing.JButton remove;
    private javax.swing.JButton save;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
